services:
  verandb:
    build: https://github.com/wichmann/veranstaltungsdatenbank_mit_mariadb.git
    image: verandb
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - VERANDB_USER=veranstaltungsdatenbank
      - VERANDB_PASSWORD=/run/secrets/verandb_db_password
      - VERANDB_DATABASE=veranstaltungsdatenbank
      - VERANDB_ROOT_PASSWORD=/run/secrets/verandb_db_root_password
    volumes:
      - verandb_data:/app
    secrets:
      - verandb_db_root_password
      - verandb_db_password

  verandb-db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_USER=veranstaltungsdatenbank
      - MARIADB_PASSWORD=/run/secrets/verandb_db_password
      - MARIADB_DATABASE=veranstaltungsdatenbank
      - MARIADB_ROOT_PASSWORD=/run/secrets/verandb_db_root_password
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - verandb_db_data:/var/lib/mysql
    secrets:
      - verandb_db_root_password
      - verandb_db_password

volumes:
  verandb_data:
  verandb_db_data:

secrets:
  verandb_db_root_password:
    file: verandb_db_root_password.txt
  verandb_db_password:
    file: verandb_db_password.txt
